In [1]:
import pandas as pd
import numpy as np

# Load resources

In [21]:
def load_pathway(fpath):
    result = []
    with open(fpath) as f:
        for line in f:
            split_line = [x for x in line.strip().split('\t') if x]  # Remove empty strings directly

            row = {'label': split_line[0]}
            for gene in split_line[1:]:
                row[gene] = 1

            result.append(row)

    df = pd.DataFrame(result)
    df = df.fillna(0.0).set_index('label').astype(bool).T  # Chained operations for clarity

    return df

mpath = "PanglaoDB_Augmented_2021.txt"
pang = load_pathway(mpath)

cell_types = [
    'Fibroblasts',
    'Myocytes',
    'Myoblasts',
    'Myofibroblasts',
]

subset = pang[cell_types]
panglao_markers = subset[subset.any(axis=1)]

panglao_markers = panglao_markers.reset_index(names='gene')

print(panglao_markers.shape)
panglao_markers.head()

# fib_genes = panglao_markers['Fibroblasts'] == True
# fib_genes =  panglao_markers[fib_genes].index
# print(f"N fib genes: {len(fib_genes)}")

# myo_genes_panglao = (panglao_markers['Myocytes'] == True) | (panglao_markers['Myoblasts'] == True)
# myo_genes_panglao =  panglao_markers[myo_genes_panglao].index
# print(f"N myocyte/myoblast genes: {len(myo_genes_panglao)}")

(451, 5)

label     gene  Fibroblasts  Myocytes  Myoblasts  Myofibroblasts
0      RARRES2         True     False      False           False
1        CELA1         True     False      False           False
2          LUM         True     False       True            True
3        PRRX1         True      True       True            True
4       SCARA5         True     False      False           False

In [5]:
# fpath = "Tabula_Sapiens.txt"

# tabula = load_pathway(fpath)
# tabula.head()


# cell_types = [
#     'Muscle-fast Muscle Cell',
#     'Muscle-slow Muscle Cell',

label,Bladder-bladder Urothelial Cell,Bladder-capillary Endothelial Cell,Bladder-endothelial Cell Of Lymphatic Vessel,Bladder-fibroblast,Bladder-macrophage,Bladder-mast Cell,Bladder-myofibroblast Cell,Bladder-nk Cell,Bladder-pericyte Cell,Bladder-plasma Cell,...,Thymus-dn4 Thymocyte,Thymus-innate Lymphoid Cell,Thymus-myeloid Dendritic Cell,Thymus-naive Regulatory T Cell,Thymus-t Follicular Helper Cell,Tongue-schwann Cell,Vasculature-artery Endothelial Cell,Vasculature-lymphatic Endothelial Cell,Eye-adipocyte,Eye-retinal Ganglion Cell
GDF15,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
RPS8,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
RPL21,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
RPS9,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
RPS6,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [8]:
# [col for col in tabula.columns if 'skeletal' in col.lower()]

['Muscle-skeletal Muscle Satellite Stem Cell', 'Skin-cell Of Skeletal Muscle']

In [9]:
fpath = "CellMarker_2024.txt"

cellmarker = load_pathway(fpath)
cellmarker.head()

label,1-Cell Stage Cell (Blastomere) Embryo Human,1-Cell Stage Cell (Blastomere) Embryo Mouse,4-Cell Stage Cell (Blastomere) Embryo Human,4-Cell Stage Cell (Blastomere) Embryo Mouse,8-Cell Stage Cell (Blastomere) Embryo Human,8-Cell Stage Cell (Blastomere) Embryo Mouse,AXL+ SIGLEC6+ Dendritic Cell Undefined Human,AXL+SIGLEC6+ Dendritic Cell Blood Human,Acinar Cell Pancreas Human,Acinar Cell Pancreatic Islet Human,...,Vascular Endothelial Cell Eye Human,Vascular Endothelial Cell Kidney Mouse,Vascular Smooth Muscle cell(VSMC) Bone Mouse,Ventral Otocyst Brain Mouse,Well-established Epicardial Progenitor Cell Heart Mouse,Wnt2+ Cell Lung Mouse,hMSC-treated B Cell Bone Marrow Human,lmmLeydig Cell Testis Human,Proliferative Mesenchymal Progenitor Cell Lung Mouse,Beta-2M - SPalpha-6 + THY1 + Spermatogonial Stem Cell Testis Mouse
KLF11,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
KLHDC3,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
BLCAP,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
PPIL2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ARHGEF16,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
[col for col in cellmarker.columns if 'myoblast' in col.lower()]

['Myoblast Muscle Human',
 'Myoblast Skeletal Muscle Human',
 'Myoblast Undefined Human']

In [11]:
[col for col in cellmarker.columns if 'fibroblast' in col.lower()]

['Cancer-associated Fibroblast Breast Human',
 'Cancer-associated Fibroblast Colorectum Human',
 'Cancer-associated Fibroblast Liver Human',
 'Cancer-associated Fibroblast Skin Human',
 'Fibroblast Aorta Mouse',
 'Fibroblast Artery Mouse',
 'Fibroblast Bile Duct Human',
 'Fibroblast Bladder Human',
 'Fibroblast Blood Vessel Mouse',
 'Fibroblast Blood Human',
 'Fibroblast Brain Human',
 'Fibroblast Breast Human',
 'Fibroblast Breast Mouse',
 'Fibroblast Colon Human',
 'Fibroblast Epithelium Human',
 'Fibroblast Esophagus Human',
 'Fibroblast Heart Muscle Mouse',
 'Fibroblast Heart Human',
 'Fibroblast Heart Mouse',
 'Fibroblast Intestine Mouse',
 'Fibroblast Kidney Human',
 'Fibroblast Kidney Mouse',
 'Fibroblast Liver Mouse',
 'Fibroblast Lung Human',
 'Fibroblast Lung Mouse',
 'Fibroblast Muscle Human',
 'Fibroblast Muscle Mouse',
 'Fibroblast Ovarian Cortex Human',
 'Fibroblast Ovary Human',
 'Fibroblast Pancreas Human',
 'Fibroblast Prostate Human',
 'Fibroblast Skin Human',
 'Fibroblast Skin Mouse',
 'Fibroblast Spleen Human',
 'Fibroblast Stomach Human',
 'Fibroblast Synovium Human',
 'Fibroblast Thymus Human',
 'Fibroblast Undefined Human',
 'Fibroblast Undefined Mouse',
 'Fibroblast Vocal Fold Human',
 'Idiopathic Pulmonary Fibrosis Myofibroblast Undefined Human',
 'Lipofibroblast Lung Mouse',
 'Matrix Fibroblast Lung Mouse',
 'Myofibroblast Bone Mouse',
 'Myofibroblast Breast Human',
 'Myofibroblast Dermis Human',
 'Myofibroblast Epithelium Human',
 'Myofibroblast Esophagus Human',
 'Myofibroblast Heart Mouse',
 'Myofibroblast Lung Human',
 'Myofibroblast Lung Mouse',
 'Myofibroblast Skin Human',
 'Myofibroblast Stomach Human',
 'Myofibroblast Tendon Mouse',
 'Myofibroblast Undefined Human',
 'Myofibroblastic Cancer Associated Fibroblast (myCAF) Pancreas Human',
 'Papillary Fibroblast Skin Human',
 'Reticular Fibroblast Skin Human']

In [20]:
cell_types = [
    'Myoblast Skeletal Muscle Human',
    'Myoblast Muscle Human',
    
    'Fibroblast Skin Human',
    
    'Myofibroblast Skin Human',
]

cdf = cellmarker[cell_types].copy()
subset = cdf[cell_types]

cellmarker_markers = subset[subset.any(axis=1)]

cellmarker_markers = cellmarker_markers.reset_index(names='gene')

cellmarker_markers.head()

label,gene,Myoblast Skeletal Muscle Human,Myoblast Muscle Human,Fibroblast Skin Human,Myofibroblast Skin Human
0,CEL,False,False,True,False
1,ID3,False,True,False,False
2,COL1A2,False,False,True,False
3,CFD,False,False,True,False
4,LUM,False,False,True,False

# Combine

In [31]:
def markers_wide_to_long(df, gene_col="gene"):
    cell_cols = df.columns.drop(gene_col)
    long = (df
            .melt(id_vars=gene_col, value_vars=cell_cols,
                  var_name="cell_type", value_name="is_marker"))
    return long[long["is_marker"]].drop(columns="is_marker").reset_index(drop=True)


long1 = markers_wide_to_long(panglao_markers).assign(source='Panglao')
long2 = markers_wide_to_long(cellmarker_markers).assign(source='CellMarker')

mdf = (pd.concat([long1, long2], ignore_index=True)
       .drop_duplicates()
       .sort_values(['cell_type', 'gene'])
       .reset_index(drop=True))

print(mdf.shape)
mdf.head()

(699, 3)

    gene              cell_type      source
0   APOD  Fibroblast Skin Human  CellMarker
1   APOE  Fibroblast Skin Human  CellMarker
2  CCL19  Fibroblast Skin Human  CellMarker
3   CCL2  Fibroblast Skin Human  CellMarker
4   CD36  Fibroblast Skin Human  CellMarker

In [32]:
# add categories
ct = (mdf["cell_type"]
      .astype("string")
      .str.normalize("NFKC")
      .str.strip()
      .str.replace(r"\s+", " ", regex=True)
      .str.lower()
)

mdf["category"] = np.select(
    [
        ct.str.contains(r"\bmyofibroblasts?\b", regex=True, na=False),
        ct.str.contains(r"\bfibroblasts?\b", regex=True, na=False),
        ct.str.contains(r"\b(myocytes?|muscles?|myoblasts?)\b", regex=True, na=False),
    ],
    ["myofibroblast", "fibroblast", "muscle"],
    default=pd.NA
)

mdf.head()

/tmp/ipykernel_3107890/1260700923.py:17: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ct.str.contains(r"\b(myocytes?|muscles?|myoblasts?)\b", regex=True, na=False),

    gene              cell_type      source    category
0   APOD  Fibroblast Skin Human  CellMarker  fibroblast
1   APOE  Fibroblast Skin Human  CellMarker  fibroblast
2  CCL19  Fibroblast Skin Human  CellMarker  fibroblast
3   CCL2  Fibroblast Skin Human  CellMarker  fibroblast
4   CD36  Fibroblast Skin Human  CellMarker  fibroblast

In [37]:
gene_cats = (mdf.dropna(subset=["category"])
             .groupby("gene")["category"]
             .agg(lambda s: sorted(set(s))))

# 2) attach and compute "other_categories?"
tmp = mdf.join(gene_cats.rename("all_categories"), on="gene")

def other_cats(row):
    cats = row["all_categories"]
    cat = row["category"]
    if not isinstance(cats, list) or pd.isna(cat):
        return pd.NA
    if len(cats) == 1:
        return "unique"
    others = [c for c in cats if c != cat]
    return ", ".join(others) if others else "unique"

mdf["other_categories?"] = tmp.apply(other_cats, axis=1)
mdf.head()

    gene              cell_type      source    category other_categories?
0   APOD  Fibroblast Skin Human  CellMarker  fibroblast            unique
1   APOE  Fibroblast Skin Human  CellMarker  fibroblast            unique
2  CCL19  Fibroblast Skin Human  CellMarker  fibroblast            unique
3   CCL2  Fibroblast Skin Human  CellMarker  fibroblast            muscle
4   CD36  Fibroblast Skin Human  CellMarker  fibroblast            unique

In [38]:
# mdf.to_csv("clean_marker_genes.csv", index=False)

In [44]:
print(f"Total muscle markers: {mdf[mdf['category'] == 'muscle']['gene'].nunique()}")
print(f"Unique muscle markers: {mdf[(mdf['category'] == 'muscle') & (mdf['other_categories?'] == 'unique')]['gene'].nunique()}")

print(f"\nTotal fibroblast markers: {mdf[mdf['category'] == 'fibroblast']['gene'].nunique()}")
print(f"Unique fibroblast markers: {mdf[(mdf['category'] == 'fibroblast') & (mdf['other_categories?'] == 'unique')]['gene'].nunique()}")

print(f"\nTotal myofibroblast markers: {mdf[mdf['category'] == 'myofibroblast']['gene'].nunique()}")
print(f"Unique myofibroblast markers: {mdf[(mdf['category'] == 'myofibroblast') & (mdf['other_categories?'] == 'unique')]['gene'].nunique()}")

Total muscle markers: 270
Unique muscle markers: 207

Total fibroblast markers: 254
Unique fibroblast markers: 166

Total myofibroblast markers: 111
Unique myofibroblast markers: 19

In [45]:
total_myo = mdf[mdf['category'] == 'muscle']['gene'].unique()
uni_myo = mdf[(mdf['category'] == 'muscle') & (mdf['other_categories?'] == 'unique')]['gene'].unique()

shared = list(set(total_myo) - set(uni_myo))

print(", ".join(shared))

HTRA1, PARVA, FBXL7, C1QTNF1, IGFBP5, CCL2, COL6A1, LAMB2, NID2, MEDAG, LAMB1, TNS2, BGN, TPM1, FLNC, PHLDB1, COL12A1, HSPB6, HSPB2, LMOD1, SULF1, MMP2, DES, ISLR, COL5A1, TIMP3, CRYAB, CALD1, COL4A1, C1QTNF5, TMEM47, PRKG1, FN1, SRPX2, COL1A1, RASL12, NNMT, COL4A2, POSTN, COX7A1, TPM2, MXRA5, ANGPTL2, PPP1R3C, SYNPO2, COL16A1, SGCD, PALLD, FSTL1, LAMA2, LUM, COL1A2, FBN1, PRRX1, NGF, MRGPRF, FKBP10, COL5A2, COL3A1, MEOX1, OLFML3, EDNRA, ENO3

In [48]:
display(mdf[mdf['gene'] == 'COL1A1'])

,gene,cell_type,source,category,other_categories?
9,COL1A1,Fibroblast Skin Human,CellMarker,fibroblast,"muscle, myofibroblast"
77,COL1A1,Fibroblasts,Panglao,fibroblast,"muscle, myofibroblast"
325,COL1A1,Myoblasts,Panglao,muscle,"fibroblast, myofibroblast"
617,COL1A1,Myofibroblasts,Panglao,myofibroblast,"fibroblast, muscle"

# Cell cycle

In [4]:
### --------- load cell cycle genes ---------

# regev
regev_genes = [x.strip() for x in open('regev_lab_cell_cycle_genes.txt')]
print(f'Total regev genes: {len(regev_genes)}')

# KEGG (hsa04110) -- downloaded from GSEA website
kdf = pd.read_json("KEGG_CELL_CYCLE.v2026.1.Hs.json")
kegg_genes = kdf.loc['geneSymbols', 'KEGG_CELL_CYCLE']
print(f'Total KEGG cell cycle genes: {len(kegg_genes)}')

Total regev genes: 97
Total KEGG cell cycle genes: 125

In [5]:
### GO biological processes
path_2023 = "../resources/GO_Biological_Process_2023.txt"
path_2025 = "/home/jrcwycy/.cache/gseapy/Enrichr.GO_Biological_Process_2025.gmt"

geneset_dict = {}

with open(path_2025, "r") as f:
    for line in f:
        parts = line.strip().split('\t')
        if len(parts) >= 1:
            term = parts[0].strip()
            genes = parts[2:] if len(parts) > 2 else []
            genes = [g.strip() for g in genes if g.strip()]
            geneset_dict[term] = genes

geneset = pd.DataFrame.from_dict(geneset_dict, orient='index').T
geneset.head()

,'De Novo' AMP Biosynthetic Process (GO:0044208),'De Novo' Post-Translational Protein Folding (GO:0051084),2-Oxoglutarate Metabolic Process (GO:0006103),3'-UTR-mediated mRNA Destabilization (GO:0061158),3'-UTR-mediated mRNA Stabilization (GO:0070935),3'-Phosphoadenosine 5'-Phosphosulfate Metabolic Process (GO:0050427),4-Hydroxyproline Metabolic Process (GO:0019471),5S Class rRNA Transcription by RNA Polymerase III (GO:0042791),7-Methylguanosine RNA Capping (GO:0009452),7-Methylguanosine Cap Hypermethylation (GO:0036261),...,Wybutosine Biosynthetic Process (GO:0031591),Wybutosine Metabolic Process (GO:0031590),Xenobiotic Catabolic Process (GO:0042178),Xenobiotic Transport (GO:0042908),Xenobiotic Transport Across Blood-Brain Barrier (GO:1990962),Zinc Ion Import Across Plasma Membrane (GO:0071578),Zinc Ion Import Into Organelle (GO:0062111),Zinc Ion Transmembrane Transport (GO:0071577),Zinc Ion Transport (GO:0006829),Zymogen Activation (GO:0031638)
0,ATIC,CCT4,IDH1,UPF1,RBM38,PAPSS1,EGLN2,GTF3C2,RNGTT,SNRPD3,...,TYW5,TYW5,UGT1A10,ABCC5,ABCC2,SLC30A8,SLC30A8,SLC30A8,SLC30A8,FGB
1,PAICS,SDF2L1,PHYH,TRIM71,DAZ4,PAPSS2,GOT2,GTF3C3,RNMT,SNRPD2,...,TYW3,TYW3,GSTM4,SLC22A4,SLC22A1,SLC39A10,SLC30A7,SLC39A1,SLC39A1,FGG
2,PFAS,CCT3,GOT2,RC3H1,TIRAP,SULT1A2,HOGA1,GTF3C4,NCBP1,SNRPF,...,TYW1,TYW1,GSTM3,ABCB1,SLC22A2,SLC39A12,SLC30A4,SLC30A4,SLC30A9,F12
3,ADSS1,HSPA9,IDH2,ZFP36L1,DAZ3,SULT1C4,P4HB,GTF3C5,CMTR2,SNRPG,...,TRMT12,TRMT12,GSTM2,ABCC2,ABCC1,SLC39A6,SLC30A3,SLC30A3,SLC30A4,ZNF160
4,ADSS2,CCT2,ADHFE1,PUM2,YBX3,SULT2A1,PRODH,GTF3C6,RAMAC,SNRPE,...,TYW1B,TYW1B,NANOS1,SLC15A2,ABCG2,SLC39A14,SLC30A6,SLC30A5,SLC30A3,F9

In [25]:
terms = ['cell cycle', 'g1/s', 'g2/m', 'g0']

[col for col in geneset if any(term in col.lower() for term in terms)]

['G1/S Transition of Mitotic Cell Cycle (GO:0000082)',
 'G2/M Transition of Mitotic Cell Cycle (GO:0000086)',
 'Cell Cycle G1/S Phase Transition (GO:0044843)',
 'Cell Cycle G2/M Phase Transition (GO:0044839)',
 'Metaphase/Anaphase Transition of Cell Cycle (GO:0044784)',
 'Metaphase/Anaphase Transition of Mitotic Cell Cycle (GO:0007091)',
 'Mitotic G1/S Transition Checkpoint Signaling (GO:0044819)',
 'Mitotic G2/M Transition Checkpoint (GO:0044818)',
 'Mitotic Cell Cycle Checkpoint Signaling (GO:0007093)',
 'Mitotic Cell Cycle Phase Transition (GO:0044772)',
 'Negative Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000134)',
 'Negative Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010972)',
 'Negative Regulation of Cell Cycle (GO:0045786)',
 'Negative Regulation of Cell Cycle G1/S Phase Transition (GO:1902807)',
 'Negative Regulation of Cell Cycle G2/M Phase Transition (GO:1902750)',
 'Negative Regulation of Cell Cycle Phase Transition (GO:1901988)',
 'Negative Regulation of Cell Cycle Process (GO:0010948)',
 'Negative Regulation of Meiotic Cell Cycle (GO:0051447)',
 'Negative Regulation of Mitotic Cell Cycle (GO:0045930)',
 'Negative Regulation of Mitotic Cell Cycle Phase Transition (GO:1901991)',
 'Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087)',
 'Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)',
 'Positive Regulation of Cell Cycle (GO:0045787)',
 'Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808)',
 'Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751)',
 'Positive Regulation of Cell Cycle Phase Transition (GO:1901989)',
 'Positive Regulation of Cell Cycle Process (GO:0090068)',
 'Positive Regulation of Metaphase/Anaphase Transition of Cell Cycle (GO:1902101)',
 'Positive Regulation of Mitotic Cell Cycle (GO:0045931)',
 'Positive Regulation of Mitotic Cell Cycle Phase Transition (GO:1901992)',
 'Positive Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090267)',
 'Positive Regulation of Nuclear Cell Cycle DNA Replication (GO:0010571)',
 'Regulation of G0 to G1 Transition (GO:0070316)',
 'Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045)',
 'Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389)',
 'Regulation of G2/MI Transition of Meiotic Cell Cycle (GO:0110030)',
 'Regulation of Cell Cycle (GO:0051726)',
 'Regulation of Cell Cycle G1/S Phase Transition (GO:1902806)',
 'Regulation of Cell Cycle G2/M Phase Transition (GO:1902749)',
 'Regulation of Cell Cycle Checkpoint (GO:1901976)',
 'Regulation of Cell Cycle Phase Transition (GO:1901987)',
 'Regulation of Cell Cycle Process (GO:0010564)',
 'Regulation of Meiotic Cell Cycle (GO:0051445)',
 'Regulation of Metaphase/Anaphase Transition of Cell Cycle (GO:1902099)',
 'Regulation of Mitotic Cell Cycle (GO:0007346)',
 'Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990)',
 'Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090266)',
 'Regulation of Nuclear Cell Cycle DNA Replication (GO:0033262)']

In [26]:
terms = ['cell cycle', 'g1/s', 'g2/m', 'g0']
cc_go = geneset[[col for col in geneset if any(term in col.lower() for term in terms)]].copy()

# remove meiosis columns
terms = ['meiosis', 'meiotic']
meiosis_cols = [col for col in cc_go if any(term in col.lower() for term in terms)]
print(len(meiosis_cols))
cc_go = cc_go.drop(columns=meiosis_cols)

print(cc_go.shape)
cc_go.head()

3
(2250, 45)

,G1/S Transition of Mitotic Cell Cycle (GO:0000082),G2/M Transition of Mitotic Cell Cycle (GO:0000086),Cell Cycle G1/S Phase Transition (GO:0044843),Cell Cycle G2/M Phase Transition (GO:0044839),Metaphase/Anaphase Transition of Cell Cycle (GO:0044784),Metaphase/Anaphase Transition of Mitotic Cell Cycle (GO:0007091),Mitotic G1/S Transition Checkpoint Signaling (GO:0044819),Mitotic G2/M Transition Checkpoint (GO:0044818),Mitotic Cell Cycle Checkpoint Signaling (GO:0007093),Mitotic Cell Cycle Phase Transition (GO:0044772),...,Regulation of Cell Cycle G1/S Phase Transition (GO:1902806),Regulation of Cell Cycle G2/M Phase Transition (GO:1902749),Regulation of Cell Cycle Checkpoint (GO:1901976),Regulation of Cell Cycle Phase Transition (GO:1901987),Regulation of Cell Cycle Process (GO:0010564),Regulation of Metaphase/Anaphase Transition of Cell Cycle (GO:1902099),Regulation of Mitotic Cell Cycle (GO:0007346),Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990),Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090266),Regulation of Nuclear Cell Cycle DNA Replication (GO:0033262)
0,CCNJL,CCDC57,CCNJL,CCDC57,CDC23,CDC23,PLK3,PABIR1,PABIR1,CCNJL,...,FBXW7,NPM1,ETAA1,CDK18,CDK18,SMARCC1,SCRIB,UBE2C,GEN1,DBF4
1,USP26,PLK1,USP26,PLK1,PLK1,PLK1,CDPF1,PLK1,NABP1,UBE2C,...,PHF10,KCNH5,RAD51,FBXW7,UVRAG,SMARCC2,RNF40,PHF10,SKA1,ATRX
2,CDC25A,USP22,CDC25A,USP22,CDC27,CDC27,PRKDC,NABP1,PLK3,CDC25A,...,SMARCE1,DYRK3,FEM1B,PLK1,SND1,PLK1,CDC25B,SMARCE1,KNL1,WIZ
3,CDC7,PLK3,CDC7,PLK3,TACC3,TACC3,RPS27L,INTS3,INTS3,UBE2A,...,TM4SF5,AURKA,POLR1B,ATP2B4,SH3GLB1,UBE2C,CDC20,MAD2L1BP,USP44,DBF4B
4,USP29,CDC25A,USP29,CDC25A,ANAPC2,ANAPC2,TRIAP1,HUS1,INIP,CDC25B,...,SMARCA2,CDPF1,RFWD3,CDPF1,RPL23,NEK6,CDC25C,TM4SF5,XRCC3,INO80

In [27]:
print(f'N terms: {len(cc_go.columns)}')
print(f'N unique genes: {len(set(cc_go.stack()))}') # drops NaNs

N terms: 45
N unique genes: 857

In [29]:
cell_cycle_groups = {
    "G0_G1_transition": [
        'Regulation of G0 to G1 Transition (GO:0070316)',
    ],
    
    "G1S_transition": [
        'G1/S Transition of Mitotic Cell Cycle (GO:0000082)',
        'Cell Cycle G1/S Phase Transition (GO:0044843)',
        'Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045)',
        'Regulation of Cell Cycle G1/S Phase Transition (GO:1902806)',
        'Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087)',
        'Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808)',
        'Negative Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000134)',
        'Negative Regulation of Cell Cycle G1/S Phase Transition (GO:1902807)',
        'Mitotic G1/S Transition Checkpoint Signaling (GO:0044819)',
    ],

    "DNA_replication_S_phase": [
        'Regulation of Nuclear Cell Cycle DNA Replication (GO:0033262)',
        'Positive Regulation of Nuclear Cell Cycle DNA Replication (GO:0010571)',
    ],

    "G2M_transition": [
        'G2/M Transition of Mitotic Cell Cycle (GO:0000086)',
        'Cell Cycle G2/M Phase Transition (GO:0044839)',
        'Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389)',
        'Regulation of Cell Cycle G2/M Phase Transition (GO:1902749)',
        'Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)',
        'Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751)',
        'Negative Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010972)',
        'Negative Regulation of Cell Cycle G2/M Phase Transition (GO:1902750)',
        'Mitotic G2/M Transition Checkpoint (GO:0044818)',
    ],

    "metaphase_anaphase_transition": [
        'Metaphase/Anaphase Transition of Cell Cycle (GO:0044784)',
        'Metaphase/Anaphase Transition of Mitotic Cell Cycle (GO:0007091)',
        'Regulation of Metaphase/Anaphase Transition of Cell Cycle (GO:1902099)',
        'Positive Regulation of Metaphase/Anaphase Transition of Cell Cycle (GO:1902101)',
    ],

    "checkpoint_spindle_assembly_checkpoint": [
        'Mitotic Cell Cycle Checkpoint Signaling (GO:0007093)',
        'Regulation of Cell Cycle Checkpoint (GO:1901976)',
        'Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090266)',
        'Positive Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090267)',
    ],
    
    "all_checkpoint": [
        'Mitotic G1/S Transition Checkpoint Signaling (GO:0044819)',
        'Mitotic G2/M Transition Checkpoint (GO:0044818)',
        'Mitotic Cell Cycle Checkpoint Signaling (GO:0007093)',
        'Regulation of Cell Cycle Checkpoint (GO:1901976)',
        'Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090266)',
        'Positive Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090267)',
    ],

    "general_cell_cycle_regulation": [
        'Regulation of Cell Cycle (GO:0051726)',
        'Positive Regulation of Cell Cycle (GO:0045787)',
        'Negative Regulation of Cell Cycle (GO:0045786)',
        'Regulation of Cell Cycle Process (GO:0010564)',
        'Positive Regulation of Cell Cycle Process (GO:0090068)',
        'Negative Regulation of Cell Cycle Process (GO:0010948)',
    ],

    "general_mitotic_cell_cycle_regulation": [
        'Regulation of Mitotic Cell Cycle (GO:0007346)',
        'Positive Regulation of Mitotic Cell Cycle (GO:0045931)',
        'Negative Regulation of Mitotic Cell Cycle (GO:0045930)',
    ],

    "general_phase_transition": [
        'Mitotic Cell Cycle Phase Transition (GO:0044772)',
        'Regulation of Cell Cycle Phase Transition (GO:1901987)',
        'Positive Regulation of Cell Cycle Phase Transition (GO:1901989)',
        'Negative Regulation of Cell Cycle Phase Transition (GO:1901988)',
        'Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990)',
        'Positive Regulation of Mitotic Cell Cycle Phase Transition (GO:1901992)',
        'Negative Regulation of Mitotic Cell Cycle Phase Transition (GO:1901991)',
    ],
}

In [30]:
# creating boolean dataframe
def get_genes_from_terms(df, terms):
    existing_terms = [t for t in terms if t in df.columns]

    vals = df[existing_terms].to_numpy().ravel()

    genes = (
        pd.Series(vals)
        .dropna()
        .astype(str)
        .str.strip()
    )

    genes = genes[genes != ""]

    return set(genes)

# collect all genes across all groups
all_genes = sorted(
    set().union(
        *[
            get_genes_from_terms(cc_go, terms)
            for terms in cell_cycle_groups.values()
        ]
    )
)

# initialize output dataframe
cell_cycle_bool = pd.DataFrame(index=all_genes)

for group_name, terms in cell_cycle_groups.items():
    genes_in_group = get_genes_from_terms(cc_go, terms)
    cell_cycle_bool[group_name] = cell_cycle_bool.index.isin(genes_in_group)

cell_cycle_bool.index.name = "gene"

print(cell_cycle_bool.shape)
cell_cycle_bool.head()

(857, 10)

,G0_G1_transition,G1S_transition,DNA_replication_S_phase,G2M_transition,metaphase_anaphase_transition,checkpoint_spindle_assembly_checkpoint,all_checkpoint,general_cell_cycle_regulation,general_mitotic_cell_cycle_regulation,general_phase_transition
gene,,,,,,,,,,
ACTL6A,False,False,False,False,False,False,False,True,False,False
ACTL6B,True,True,False,False,True,False,False,True,False,True
ACTR5,False,False,False,False,False,False,False,True,False,False
ACTR8,False,False,False,False,False,False,False,True,False,False
ACVR1,False,True,False,False,False,False,False,False,False,False

In [31]:
cell_cycle_bool.to_csv("GO_2025_cc_genes.csv")

In [13]:
terms = ['g1/s transition', 'g1/s phase transition']

g1s_transition_terms = [col for col in geneset if any(term in col.lower() for term in terms)]
g1s_transition_terms

['G1/S Transition of Mitotic Cell Cycle (GO:0000082)',
 'Cell Cycle G1/S Phase Transition (GO:0044843)',
 'Mitotic G1/S Transition Checkpoint Signaling (GO:0044819)',
 'Negative Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000134)',
 'Negative Regulation of Cell Cycle G1/S Phase Transition (GO:1902807)',
 'Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087)',
 'Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808)',
 'Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045)',
 'Regulation of Cell Cycle G1/S Phase Transition (GO:1902806)']

In [14]:
terms = ['g2/m transition', 'g2/m phase transition']

g2m_transition_terms = [col for col in geneset if any(term in col.lower() for term in terms)]
g2m_transition_terms

['G2/M Transition of Mitotic Cell Cycle (GO:0000086)',
 'Cell Cycle G2/M Phase Transition (GO:0044839)',
 'Mitotic G2/M Transition Checkpoint (GO:0044818)',
 'Negative Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010972)',
 'Negative Regulation of Cell Cycle G2/M Phase Transition (GO:1902750)',
 'Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)',
 'Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751)',
 'Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389)',
 'Regulation of Cell Cycle G2/M Phase Transition (GO:1902749)']

In [15]:
terms = ['metaphase/anaphase transition', 'metaphase/anaphase phase transition']

ma_transition_terms = [col for col in geneset if any(term in col.lower() for term in terms)]
ma_transition_terms

['Metaphase/Anaphase Transition of Cell Cycle (GO:0044784)',
 'Metaphase/Anaphase Transition of Mitotic Cell Cycle (GO:0007091)',
 'Negative Regulation of Mitotic Metaphase/Anaphase Transition (GO:0045841)',
 'Positive Regulation of Metaphase/Anaphase Transition of Cell Cycle (GO:1902101)',
 'Positive Regulation of Mitotic Metaphase/Anaphase Transition (GO:0045842)',
 'Regulation of Metaphase/Anaphase Transition of Cell Cycle (GO:1902099)',
 'Regulation of Mitotic Metaphase/Anaphase Transition (GO:0030071)']